language: node_js

node_js:
  - '0.10'

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate < test/coverage/**/lcov.info

notifications:
  # publish build status to IRC channel: #vidbg
  irc:
    channels:
    - chat.freenode.net#vidbg
    on_success: always
    on_failure: always
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  # publish build status to gitter chat room: https://gitter.im/daniellmb/vidbg
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9534185ec0307ae1a6c8
    on_success: always
    on_failure: always
    on_start: false

env:
  - CODECLIMATE_REPO_TOKEN=df4f92633881e79740616783a7cf94798a0b7706ee591a13cb11e8eebbd3b92b